# Generated by Django 4.0.6 on 2022-07-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photo', models.FileField(upload_to='news/')),
            ],
            options={
                'verbose_name': 'new',
                'verbose_name_plural': 'news',
            },
        ),
    ]
